# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
  branches:
    master:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - apt-get update -qq && apt-get install -y curl
            - curl -L https://fly.io/install.sh | sh
            - export FLYCTL_INSTALL="/root/.fly"
            - export PATH="$FLYCTL_INSTALL/bin:$PATH"
            #- wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && dpkg -i erlang-solutions_2.0_all.deb
            #- apt-get update
            #- apt-get install esl-erlang
            #- apt-get install elixir
            #- mix setup
            - flyctl deploy --remote-only